* B.Z. Berlin

  :FEEDSTATUS:
(("http://www.bz-berlin.de/?p=3437816" t "5aa66980d752c15ff242ac33d38b0af994954f25")
 ("http://www.bz-berlin.de/?p=3437861" t "96ae265959ad6a5bc6bee00b853394b691adbeb5")
 ("http://www.bz-berlin.de/?p=3437836" t "140be803fd5b6cafd28edd4fec62f5a0975f17b8")
 ("http://www.bz-berlin.de/?p=3437663" t "52c825da4ee645234645f1c94d48fbdc7ab974a5")
 ("http://www.bz-berlin.de/?p=3437725" t "87163a9f237ec671b4fccb67a40c122d28e02256")
 ("http://www.bz-berlin.de/?p=3437732" t "b8b879d132fdccf96b0f187d95d23b2e31516f30")
 ("http://www.bz-berlin.de/?p=3437758" t "9ad1bf08e5034a4655e5fc3abd4e70761309c387")
 ("http://www.bz-berlin.de/?p=3437749" t "ec06c2678cd242be196d29e3577c15833b74a62d")
 ("http://www.bz-berlin.de/?p=3436100" t "d59526426567fc0a4e74d997556f3882983c277f")
 ("http://www.bz-berlin.de/?p=3437735" t "3ab5cf5f3a38304f6d98afef90c7856332f08c4c")
 ("http://www.bz-berlin.de/?p=3437726" t "7fed0d44a84a37a53541a7a0f91dd8a0fa92fa64")
 ("http://www.bz-berlin.de/?p=3437709" t "6ca216eeb0b3a2741196a3455398772de8570f41")
 ("http://www.bz-berlin.de/?p=3437690" t "f817749c4830a2b3598a0d29f3ccfc7e9e21c90e")
 ("http://www.bz-berlin.de/?p=3437652" t "a65dee968d12b227e4fed649b890470564eb1d38")
 ("http://www.bz-berlin.de/?p=3437675" t "a0943df9199d3adf033906f7ebf803d3b9d8afe0")
 ("http://www.bz-berlin.de/?p=3437496" t "6fec2f07e5ed88c56cb9a1a5fe67f475ad3a3ed6")
 ("http://www.bz-berlin.de/?p=3437640" t "d227aac93531b6fef6d636e46345baa6c57548ed")
 ("http://www.bz-berlin.de/?p=3437585" t "c23ebe6c57de9f53aabe6936916856d174deaf5c")
 ("http://www.bz-berlin.de/?p=3437579" t "d1b307e7216645c847fa18438109b06dcbcd92d0")
 ("http://www.bz-berlin.de/?p=3437590" t "059e55bc41af1cdf37bd8adc4e8fab05a0d65e99"))
  :END:
** Prügel-Eklat beim Punktsieg von Arthur Abraham
   [2017-04-23 Sun 18:25]
                           <![CDATA[Beim einstimmigen Punktsieg gegen Robin Krasniqi kam es zu Schlägereien unter den Zuschauern. Für Abraham reichten an diesemAbend 70 Prozent.]]>
                       
   [[http://www.bz-berlin.de/berlin-sport/mehr-berlin-sport/pruegel-eklat-beim-punktsieg-von-arthur-abraham]]


** Was uns die neuen Bilder von „Game of Thrones“ verraten
   [2017-04-23 Sun 18:30]
                           <![CDATA[HBO hat nun erste Bilder der siebten Staffel veröffentlicht. Bei genauer Betrachtung lassen sich doch einige Details feststellen. Und es werden neue Fragen aufgeworfen.]]>
                       
   [[http://www.bz-berlin.de/kultur/fernsehen/was-uns-die-neuen-bilder-von-game-of-thrones-verraten]]


** Crash auf Buckower Damm: Ein Fahrer verletzt, der andere floh
   [2017-04-23 Sun 19:05]
                           <![CDATA[Auf dem Buckower Damm kollidierten zwei Fahrzeuge miteinander und rammten anschließend noch einen parkenden Porsche.]]>
                       
   [[http://www.bz-berlin.de/berlin/neukoelln/crash-auf-buckower-damm-ein-fahrer-verletzt-der-andere-soll-geflohen-sein]]


** Vedad Ibisevic ist Herthas Alleskönner
   [2017-04-23 Sun 19:06]
                           <![CDATA[Herthas Leitwolf trifft nicht nur zum Sieg gegen Wolfsburg. Der Berliner Kapitän schützt auch seine Mitspieler, wenn es einmal eng wird.]]>
                       
   [[http://www.bz-berlin.de/berlin-sport/hertha-bsc/vedad-ibisevic-ist-herthas-alleskoenner]]


** Warum ließ Union Stuttgart-Torjäger Terodde einst gehen?
   [2017-04-23 Sun 19:34]
                           <![CDATA[Simon Terodde kickte drei Jahre lang für Union. Am Montag ist der Stürmer die größte Gefahr für die Eisernen im Top-Spiel beim VfB Stuttgart.]]>
                       
   [[http://www.bz-berlin.de/berlin-sport/union-berlin/warum-liess-union-stuttgart-torjaeger-terodde-einst-gehen]]


** Friedman: Dass Le Pen so weit kam, muss uns eine Warnung sein
   [2017-04-23 Sun 20:24]
                           <![CDATA[Die Rechtspopulistin Marine Le Pen geht in Frankreich gegen Emmanuel Macron in die Stichwahl. Für Friedmann ein weiterer Erfolg für die extremistische Rechte Europas.]]>
                       
   [[http://www.bz-berlin.de/welt/friedman-dass-le-pen-so-weit-kam-muss-uns-eine-warnung-sein]]


** Frankreich: Macron und Le Pen gehen in die Stichwahl
   [2017-04-23 Sun 20:47]
                           <![CDATA[Erste Runde der Präsidentschaftswahl in Frankreich: Der Liberale und europafreundliche Macron siegt vor der Rechtspopulistin Le Pen. Die Stichwahl am 7. Mai entscheidet.]]>
                       
   [[http://www.bz-berlin.de/welt/frankreich-macron-und-le-pen-gehen-in-die-stichwahl]]


** 3:2! Barcelona gewinnt gegen Real den Clásico
   [2017-04-23 Sun 21:05]
                           <![CDATA[Mit dem Sieg verdrängte Barcelona Real Madrid von der Tabellenspitze. Doppelpack von Messi, Sergio Ramos mit Gelb-Rot vom Platz.]]>
                       
   [[http://www.bz-berlin.de/sport/fussball/32-barcelona-gewinnt-gegen-real-den-clasico]]


** Vor dieser Berlinerin zittern die Kunstfälscher
   [2017-04-23 Sun 21:06]
                           <![CDATA[Traude Sauer (74) aus Moabit spürte u. a. verschollen geglaubte Nazi-Skulpturen auf. Zum Unmut einiger Kunsthändler, denen sie so die Geschäftsgrundlage nimmt.]]>
                       
   [[http://www.bz-berlin.de/berlin/mitte/vor-dieser-berlinerin-zittern-die-kunstfaelscher]]


** Ex-Minister Wolfgang Fürniß ist tot
   [2017-04-23 Sun 21:12]
                           <![CDATA[2002 stürz­te Für­niß über einen Mil­lio­nen-Kre­dit von einem ara­bi­schen Scheich. Er kam in Haft.]]>
                       
   [[http://www.bz-berlin.de/berlin/umland/ex-minister-fuerniss-tot]]


** Zu betrunken zum Stehen – Aber Autofahren…
   [2017-04-23 Sun 21:53]
                           <![CDATA[Aufgrund seiner erheblichen Alkoholisierung bekam er vermutlich die sanfte Kurve nicht. Und raste mit dem Wagen direkt in den Wald hinein. ]]>
                       
   [[http://www.bz-berlin.de/berlin/treptow-koepenick/zu-betrunken-zum-stehen-aber-autofahren]]


** Berlin-News: Was gestern geschah und heute wichtig wird
   [2017-04-24 Mon 00:42]
                           <![CDATA[In der Nacht endete eine Suff-Fahrt in einem Wald in Karlshorst. Der Fahrer konnte kaum stehen, so alkoholisiert war er. Alle Infos aus der Nacht und was heute los ist, finden Sie hier.]]>
                       
   [[http://www.bz-berlin.de/berlin/berlin-news-was-gestern-geschah-und-heute-wichtig-wird-2017-04-24]]


** Mitsingen in der Ufa-Fabrik oder zuhören im Admiralspalast
   [2017-04-24 Mon 05:02]
                           <![CDATA[In der Ufa-Fabrik gibt es mal wieder "Schalala"-Mitgesinge – und im Admiralspalast gibt es ein großartiges neues Musical zu sehen.]]>
                       
   [[http://www.bz-berlin.de/kultur/mehr-kultur/mitsingen-in-der-ufa-fabrik-oder-zuhoeren-im-admiralspalast]]


** Nationalelf-Comeback für Max Kruse? Das sagt Jogi Löw
   [2017-04-24 Mon 05:31]
                           <![CDATA[ Bundestrainer Joachim Löw hat Bremens Torjäger Max Kruse nach dessen Vier-Tore-Gala Hoffnungen auf eine Rückkehr in die deutsche Fußball-Nationalmannschaft beim Confed Cup gemacht.]]>
                       
   [[http://www.bz-berlin.de/sport/fussball/nationalelf-comeback-fuer-max-kruse-das-sagt-jogi-loew]]


** Räuber mit Machete überfällt Wettbüro
   [2017-04-24 Mon 05:41]
                           <![CDATA[Ein mit einer Machete bewaffneter Räuber hat ein Wettbüro in Berlin-Reinickendorf überfallen.]]>
                       
   [[http://www.bz-berlin.de/berlin/reinickendorf/raeuber-mit-machete-ueberfaellt-wettbuero]]


** Anti-Sex-Zaun für Gymnasium, um Freier und Fixer fernzuhalten
   [2017-04-24 Mon 05:51]
                           <![CDATA[Schulstadtrat Carsten Spallek will einen 1,80 m hohen Zaun um das Französische Gymnasium bauen lassen, damit Freier und Fixer das Gelände in Tiergarten nicht mehr betreten können.]]>
                       
   [[http://www.bz-berlin.de/berlin/mitte/anti-sex-zaun-fuer-gymnasium-um-freier-und-fixer-fernzuhalten]]


** In „Honigfrauen“ hat Sonja Gerhardt ihre nächste große Rolle
   [2017-04-24 Mon 06:19]
                           <![CDATA[In dem DDR-Drama spielt die gebürtige Westberlinerin ein Ostmädchen, das mit seiner Freundin einen Urlaub am Balaton verbringt. Während der Dreharbeiten lernte Gerhardt die Jugendzeit ihrer Eltern ein Stückchen besser kennen. ]]>
                       
   [[http://www.bz-berlin.de/kultur/fernsehen/in-honigfrauen-hat-sonja-gerhardt-ihre-naechste-grosse-rolle]]


** Lesben und Schwule sagen in Berlin immer häufiger Ja
   [2017-04-24 Mon 06:19]
                           <![CDATA[Die Zahl der eingetragenen Lebenspartnerschaften nimmt zu. Die meisten gleichgeschlechtlichen Ehen sind in Schöneberg registriert.]]>
                       
   [[http://www.bz-berlin.de/berlin/tempelhof-schoeneberg/lesben-und-schwule-sagen-i-berlin-immer-haeufiger-ja]]

** Nach Schlägerei am Bahnhof Wuhletal sucht die Bundespolizei Zeugen
   [2017-04-24 Mon 12:36]
                           <![CDATA[Vier junge Männer wurden in Marzahn-Hellersdorf angegriffen, nachdem sie ein Trio aufforderten, einen Rettungswagen für eine hilflose Frau zu rufen.]]>
                      
   [[http://www.bz-berlin.de/berlin/marzahn-hellersdorf/nach-schlaegerei-am-bahnhof-wuhletal-sucht-die-bundespolizei-zeugen]]


** Ladendieb entpuppt sich als Tatverdächtiger in zwei Mordfällen
   [2017-04-24 Mon 12:38]
                           <![CDATA[Anfang Februar wurde ein Mann bei einem Ladendiebstahl in Neukölln aufgegriffen. Nun ergaben Ermittlungen: Er könnte in zwei Fällen Männer umgebracht haben!]]>
                      
   [[http://www.bz-berlin.de/berlin/neukoelln/ladendieb-entpuppt-sich-als-tatverdaechtiger-in-zwei-mordfaellen]]


** Sido spielt Hauptrolle in Roma-Tragikkomödie
   [2017-04-24 Mon 12:50]
                           <![CDATA[Der Berliner Rapper Sido (36, „Mein Block”) spielt die Hauptrolle in der TV-Tragikkomödie „Eine Braut kommt selten allein”. ]]>
                      
   [[http://www.bz-berlin.de/kultur/fernsehen/sido-spielt-hauptrolle-in-roma-tragikkomoedie]]


** Hertha-Coach Dardai: „Ich sehe im Training nicht die Dynamik“
   [2017-04-24 Mon 13:11]
                           <![CDATA[Zwei Bundesliga-Kurzeinsätze mit insgesamt 39 Minuten stehen in der Bilanz von Ondrej Duda. Dabei galt der Slowake als Herthas Top-Transfer aus dem letzten Sommer.]]>
                      
   [[http://www.bz-berlin.de/berlin-sport/hertha-bsc/hertha-coach-dardai-ich-sehe-im-training-nicht-die-dynamik]]


** Wenn Union in Führung geht, haben sie noch nie verloren
   [2017-04-24 Mon 13:26]
                           <![CDATA[Wie groß sind die Chancen, dass Union am Montagabend in Stuttgart punktet? Zumindest sind die Eisernen nach dem Sieg gegen Kaiserslautern zurück im Aufstiegsrennen.]]>
                      
   [[http://www.bz-berlin.de/berlin-sport/union-berlin/wenn-union-in-fuehrung-geht-haben-sie-noch-nie-verloren]]


** Kriminalstatistik: Zahl politisch motivierter Straftaten erneut gestiegen
   [2017-04-24 Mon 13:34]
                           <![CDATA[Die Zahl politisch motivierter Straftaten in Deutschland ist erneut gestiegen. 41.549 Delikte bedeuten einen Höchststand.]]>
                      
   [[http://www.bz-berlin.de/deutschland/kriminalstatistik-zahl-politisch-motivierter-straftaten-erneut-gestiegen]]


** Wenn er will, aber nicht immer kann
   [2017-04-24 Mon 14:01]
                           <![CDATA[Auch beim Mann kann durchaus Flaute im Bett sein. Kein Grund zur Sorge]]>
                      
   [[http://www.bz-berlin.de/erotik/wenn-er-will-aber-nicht-immer-kann]]


** London-Marathon: Matthew Rees hilft taumelndem Läufer ins Ziel
   [2017-04-24 Mon 14:12]
                           <![CDATA[Das muss dieser Sportsgeist sein, den man im Profi-Sport so oft vermisst. Ein Teilnehmer des London-Marathons half einem Taumelnden Läufer ins Ziel.]]>
                      
   [[http://www.bz-berlin.de/panorama/london-marathon-matthew-rees-hilft-taumelndem-laeufer-ins-ziel]]


** Wütender Raser tritt Blitzer um und rast auf Polizisten zu
   [2017-04-24 Mon 14:37]
                           <![CDATA[Ein verärgerter Autofahrer hat bei Neuzelle erst einen Blitzer umgetreten und dann beinahe einen Polizisten umgefahren. Gegen ihn wird strafrechtlich ermittelt.]]>
                      
   [[http://www.bz-berlin.de/tatort/wuetender-raser-tritt-blitzer-um-und-rast-auf-polizisten-zu]]


** Bei der Suche nach Verbrechern sind Berlins Polizisten die Hände gebunden
   [2017-04-24 Mon 15:29]
                           <![CDATA[Wenn ein Polizist in Berlin ein Auto an die Seite winkt, darf er streng genommen nur die Verkehrstüchtigkeit des Fahrzeugs und die Papiere des Halters überprüfen. Mehr nicht. Er darf weder das Handschuhfach öffnen noch den Kofferraum durchsuchen. In Bayern ist das anders. Dort gibt es das Instrument der sogenannten Schleierfahndung. Dort dürfen Polizisten Autos […]]]>
                      
   [[http://www.bz-berlin.de/berlin/kolumne/bei-der-suche-nach-verbrechern-sind-berlins-polizisten-die-haende-gebunden]]


** Fußgänger von LKW erfasst und schwer verletzt
   [2017-04-24 Mon 15:39]
                           <![CDATA[Am Montag Vormittag erfasste ein LKW beim Abbiegen einen Fußgänger. Der Mann wurde schwer verletzt in ein Krankenhaus gebracht.]]>
                      
   [[http://www.bz-berlin.de/berlin/steglitz-zehlendorf/fussgaenger-von-lkw-erfasst-und-schwer-verletzt]]


** Zlatan Ibrahimovic: „Ich werde sogar stärker zurückkommen“
   [2017-04-24 Mon 15:45]
                           <![CDATA["Ich werde dem Fußball eine Weile fehlen", schreibt Zlatan Ibrahimovic nach seiner schweren Verletzung auf Instagram. "Eine Weile", denn ans Aufhören denkt er noch lange nicht.]]>
                      
   [[http://www.bz-berlin.de/sport/fussball/zlatan-ibrahimovic-ich-werde-sogar-staerker-zurueckkommen]]


** Liebe AfD-Politiker: Hier tagt die BVV in Kreuzberg
   [2017-04-24 Mon 16:07]
                           <![CDATA[Drei AfD-Politiker wurden in die Bezirksverordnetenversammlung Kreuzberg-Friedrichshain gewählt, doch bei der Arbeit in den Ausschüssen fehlen sie meistens.]]>
                      
   [[http://www.bz-berlin.de/berlin/friedrichshain-kreuzberg/liebe-afd-politiker-hier-tagt-die-bvv-in-kreuzberg]]


** VfB Stuttgart – Union Berlin im Liveticker 2:0
   [2017-04-24 Mon 16:09]
                           <![CDATA[Union Berlin kann mit einem Sieg beim VfB Stuttgart auf Tabellenplatz eins springen. Drei Punkte wären ein wichtiger Schritt im Aufstiegsrennen. Für Köpenicker und Schwaben dabei: der B.Z.-Liveticker!]]>
                      
   [[http://www.bz-berlin.de/sport/liveticker/vfb-stuttgart-union-berlin-im-liveticker]]


** Flughafen Schönefeld: Terminal A wegen Koffer kurzzeitig gesperrt
   [2017-04-24 Mon 16:51]
                           <![CDATA[Wegen eines herrenlosen Koffers am Terminal A am es am Montagabend zu Behinderungen am Flughafen Schönefeld. Auch der Busverkehr war betroffen.]]>
                      
   [[http://www.bz-berlin.de/berlin/umland/flughafen-schoenefeld-terminal-a-wegen-koffer-kurzzeitig-gesperrt]]


** Gabriel gedenkt Holocaus-Opfern in Yad Vashem
   [2017-04-24 Mon 16:55]
                           <![CDATA[Außenminister Gabriel besucht am Holocaust-Gedenktag Jerusalem. In Auschwitz erinnerten Überlebende an die Verbrechen der Nazis.]]>
                      
   [[http://www.bz-berlin.de/welt/gabriel-gedenkt-holocaus-opfern-in-yad-vashem]]


** Der Plan steht: Die Berliner Staatsoper eröffnet im Herbst
   [2017-04-24 Mon 17:41]
                           <![CDATA[Es gibt eine große Premierenfeier und ein gefeierter Dirigent wird das Orchester leiten – trotzdem soll die Staatsoper nach den Feierlichkeiten zunächst wieder schließen.]]>
                      
   [[http://www.bz-berlin.de/berlin/mitte/der-plan-steht-die-berliner-staatsoper-eroeffnet-im-herbst]]


** Wir sind obdachlos, weil im Frauenhaus kein Platz ist
   [2017-04-24 Mon 17:43]
                           <![CDATA[Ann (30) aus Kenia erzählt der B.Z. ihre traurige Geschichte: Sie floh vor einer schwierigen Beziehung und sitzt nun auf der Straße.]]>
                      
   [[http://www.bz-berlin.de/berlin/friedrichshain-kreuzberg/wir-sind-obdachlos-weil-im-frauenhaus-kein-platz-ist]]


** Radfahrer wird von Tram erfasst und schwer verletzt
   [2017-04-24 Mon 18:25]
                           <![CDATA[Ein Radfahrer ist in Mitte mit einer Tram zusammengestoßen und wurde schwer verletzt. Der genaue Unfallhergang ist noch nicht geklärt.]]>
                      
   [[http://www.bz-berlin.de/berlin/mitte/radfahrer-wird-von-tram-erfasst-und-schwer-verletzt]]


** Muss Facebook Nutzerdaten Verstorbener preisgeben?
   [2017-04-24 Mon 18:40]
                           <![CDATA[Eine Mutter klagt gegen Facebook um die Herausgabe der Nutzerdaten ihrer verstorbenen Tochter. Sie erhofft sich Informationen über die Todesumstände.]]>
                      
   [[http://www.bz-berlin.de/berlin/berliner-kammergericht-muss-facebook-nutzerdaten-verstorbener-preisgeben]]

** Aufgepasst Hertha! Auf Platz sechs lauert Gefahr
   [2017-04-24 Mon 19:35]
                           <![CDATA[Frankfurt oder Gladbach zieht heute ins Pokalfinale ein. Holt einer der Klubs den Pott, drohen Folgen für Herthas Traum von Europa.]]>
                      
   [[http://www.bz-berlin.de/berlin-sport/hertha-bsc/aufgepasst-hertha-auf-platz-sechs-lauert-gefahr]]


** Hals-OP! Darum fehlt Zachrisson wirklich so lange
   [2017-04-24 Mon 19:36]
                           <![CDATA[Seit Wochen fehlt der Schwede Mattias Zachrisson den Füchsen. Es ist weiter offen, ob er am Mottwoch gegen Hannover spielen kann.]]>
                      
   [[http://www.bz-berlin.de/berlin-sport/fuechse-berlin/hals-op-darum-fehlt-zachrisson-wirklich-so-lange]]


** Kriminelle sprengen Tresorraum in Paraguay mit Flak auf
   [2017-04-24 Mon 20:04]
                           <![CDATA[Ein vergleichbares Verbrechen habe es in Paraguay noch nicht gegeben, sagte der zuständige Gouverneur. Mit einem Flugabwehrgeschütz sprengten die Krimiellen einen Tresor auf.]]>
                      
   [[http://www.bz-berlin.de/welt/kriminelle-erbeuten-mehrere-millionen-dollar-in-paraguay]]


** 1:3! Union verliert im Aufstiegsduell beim VfB Stuttgart
   [2017-04-24 Mon 20:10]
                           <![CDATA[Das war anders geplant. Union Berlin verliert beim VfB Stuttgart und damit an Boden im Aufstiegsrennen. Die Eisernen haben nun drei Punkte Rückstand auf Platz zwei.]]>
                      
   [[http://www.bz-berlin.de/berlin-sport/union-berlin/13-union-verliert-im-aufstiegsduell-beim-vfb-stuttgart]]


** Telefonbuch mit Tausenden Promi-Kontakten zu versteigern
   [2017-04-24 Mon 22:38]
                           <![CDATA[Von Madonna über Johnny Depp bis hin zu Leonardo DiCaprio: Der 2004 verstorbene Marlon Brando pflegte seine Kontakte gut. Sein persönliches Telefonbuch mit den Nummern tausender Promis wird nun versteigert.]]>
                      
   [[http://www.bz-berlin.de/leute/telefonbuch-mit-tausenden-promi-kontakten-zu-versteigern]]


** Die Berlin-News aus der Nacht und was heute wichtig wird
   [2017-04-25 Tue 03:39]
                           <![CDATA[In der vergangenen Nacht gab es einen Unfall mit zwei Verletzten in der Hermannstraße. Am heutigen Dienstag kommt Ivanka Trump nach Berlin. Was in der Nacht geschah und was heute los ist, erfahren Sie hier.]]>
                      
   [[http://www.bz-berlin.de/berlin/berlin-news-was-gestern-geschah-und-heute-wichtig-wird-2017-4-25]]


** Elton John muss wegen schwerer Infektion Konzerte absagen
   [2017-04-25 Tue 03:58]
                           <![CDATA[Pop-Star Elton John (70) muss wegen einer „gefährlichen und ungewöhnlichen” bakteriellen Infektion geplante Konzerte in Kalifornien und Las Vegas absagen.]]>
                      
   [[http://www.bz-berlin.de/kultur/musik/elton-john-muss-wegen-schwerer-infektion-konzerte-absagen]]


** AirBnB brachte letztes Jahr 600.000 Touristen nach Berlin
   [2017-04-25 Tue 04:23]
                           <![CDATA[Über Airbnb haben nach Angaben des Unternehmens im vergangenen Jahr rund 600.000 Gäste private Unterkünfte in Berlin gebucht. Nach Hochrechnungen des Vermittlungsportals ließen die Besucher etwa 438 Millionen Euro in der Stadt.]]>
                      
   [[http://www.bz-berlin.de/berlin/airbnb-brachte-letztes-jahr-600-000-touristen-nach-berlin]]


** Die „Blonde Ambition“: So hat Madonna mal angefangen
   [2017-04-25 Tue 04:54]
                           <![CDATA[Unter dem Titel „Blonde Ambition” sollen die Anfänge von Madonnas Karriere in den 1980er Jahren verfilmt werden.]]>
                      
   [[http://www.bz-berlin.de/kultur/film/die-blonde-ambition-so-hat-madonna-mal-angefangen]]


** Musik von Ella Fitzgerald oder von Gayle Tufts?
   [2017-04-25 Tue 05:10]
                           <![CDATA[Im Wintergarten wird der 100. Geburtstag von Ella Fitzgerald gefeiert, im Tipi rettet Gayle Tufts die Welt.]]>
                      
   [[http://www.bz-berlin.de/kalender/musik-von-ella-fitzgerald-oder-von-gayle-tufts]]


** Wie Berliner Forscher marode Brücken retten wollen
   [2017-04-25 Tue 06:11]
                           <![CDATA[Wissenschaftler der Bundesanstalt für Materialforschung und -prüfung haben einen Sensor entwickelt, der Korrosion in Beton frühzeitig erkennt. Mit vergleichsweise kleinem Aufwand können so marode Brücken besser erkannt werden.]]>
                      
   [[http://www.bz-berlin.de/berlin/ein-berlin-wird-ein-sensor-entwickelt-der-bruecken-zum-sprechen-bringen-soll]]


** Zwei Hinrichtungen an einem Tag in Arkansas
   [2017-04-25 Tue 06:16]
                           <![CDATA[Zum ersten Mal seit 16 Jahren werden zwei Verurteilte in Arkansas in weniger als 24 Stunden mit der Giftspritze hingerichtet. Der Grund? Der Nachschub für den Giftcocktail wird knapp. ]]>
                      
   [[http://www.bz-berlin.de/panorama/zwei-hinrichtungen-an-einem-tag-in-arkansas]]


** So läuft der Tag von Ivanka Trump in Berlin ab
   [2017-04-25 Tue 06:42]
*** So läuft der Tag von Ivanka Trump in Berlin ab | 
    [2017-04-25 Tue 06:42]
                           
    Die Tochter und Beraterin von US-Präsident Donald Trump, Ivanka, ist in Berlin, wird am Mittag auf dem Frauen-Gipfel „Women20 Summit” mit Merkel und Lagarde zusammentreffen. Wer ist die Frau, die inzwischen als eine der mächtigsten der Welt gilt?
                      
    [[http://www.bz-berlin.de/berlin/so-laeuft-der-tag-von-ivanka-trump-in-berlin-ab]]
*** word
    - läuft ab
      - ablaufen
	- expire
    - Gipfel
      - height
    - mächtig
      - powerful
    - gilt
      - gelten
	- be valid, be directed at

*** translation
    The daughter and consultant of U.S President Donald Trump, Ivanka is in Berlin and She will meet with the Merkel and Lagarde at the Woman-day "Woman20 Summit". Who is the lady among them, who affects the most powerfully in the world?

** Gnihihi: Jan Böhmermann muss zensiert werden
   [2017-04-25 Tue 06:48]
                           <![CDATA[In Deutschland sind die Regeln eben lockerer: Bei seinem ersten Auftritt im US-Fernsehen hat Jan Böhmermann ein Schimpfwort gleich mehrfach fallen lassen. ]]>
                      
   [[http://www.bz-berlin.de/deutschland/gnihihi-jan-boehmermann-muss-zensiert-werden]]


** Türkei bittet Deutschland um Wirtschaftshilfe
   [2017-04-25 Tue 08:09]
                           <![CDATA[Erdogans Nazi-Vorwürfe? Ein inhaftierter deutscher Journalist? War da was? Trotz vieler aktueller Streitpunkte bittet der türkische Vize-Regierungschef um deutsche Unterstützung: „Dafür brauchen wir Deutschland.”]]>
                      
   [[http://www.bz-berlin.de/welt/tuerkei-bittet-deutschland-um-wirtschaftshilfe]]


** Berlin-Friedrichshain: Die wichtige Rückkehr der Hirschmänner
   [2017-04-25 Tue 08:14]
                           <![CDATA[Mit diesem blauen Schild kehrt die Erinnerung zurück: In einem Jahr wird der Siegfried-Hirschmann-Platz mitten in Berlins größtem Neubau-Kiez liegen. Dort, nahe der Boxhagener Straße, gab's am Montag ein Richtfest für 640 Wohnungen.]]>
                      
   [[http://www.bz-berlin.de/berlin/friedrichshain-kreuzberg/berlin-friedrichshain-die-wichtige-rueckkehr-der-hirschmaenner]]


** Film-Komponist Howard Shore vertont „Herr der Ringe“ live
   [2017-04-25 Tue 08:17]
                           <![CDATA[Howard Shore komponierte die Filmmusik für die "Herr der Ringe"-Trilogie. Jetzt wird der Film wieder gezeigt, begleitet von einem Orchester. Die B.Z. traf den Kanadier zum Interview.]]>
                      
   [[http://www.bz-berlin.de/kultur/film-komponist-howard-shore-vertont-herr-der-ringe-live]]


** Die Anklage gegen den U-Bahn-Treter steht!
   [2017-04-25 Tue 08:25]
                           <![CDATA[Svetoslav S. soll im Oktober 2016 eine Frau im U-Bahnhof Hermannstraße die Treppe heruntergetreten haben. Der Staatsanwalt hat nun Anklage erhoben - wegen gefährlicher Körperverletzung.]]>
                      
   [[http://www.bz-berlin.de/berlin/neukoelln/die-anklage-gegen-den-u-bahn-treter-steht]]

** Die BVG fährt Schwarz und das ist gut so
   [2017-04-25 Tue 13:29]
                           <![CDATA[Erst am Mittwoch wird es offiziell: Auch 2016 machte die BVG Gewinn, fuhr schwarze Zahlen ein. Der Konzern erzielte einen Überschuss von 21 Millionen Euro. Ein Teil des Geldes ist aber schon geblockt.]]>
                      
   [[http://www.bz-berlin.de/berlin/die-bvg-faehrt-schwarz-und-das-ist-gut-so]]


** U-Bahn-Treter masturbierte vor zwei Frauen
   CLOCK: [2017-04-25 Tue 23:45]
   [2017-04-25 Tue 13:35]

*** U-Bahn-Treter masturbierte vor zwei Frauen | U-Bahn-Crimer masturbated before two Ladies
    [2017-04-25 Tue 13:35]

    訳していてホントかよ案件。B.Zがドイツの東スポと言われているのを思い出した。
    
    Svetoslav S. soll im Oktober 2016 eine Frau im U-Bahnhof Hermannstraße die Treppe heruntergetreten haben. Angeklagt wird der Mann nun wegen gefährlicher Körperverletzung und Exhibitionismus. Er soll vor einer Frau masturbiert haben.
                      
    [[http://www.bz-berli n.de/berlin/neukoelln/u-bahn-treter-von-der-hermannstrasse-wird-auch-als-exhibitionist-angeklagt]]

*** translation
    Svetoslav S. is thought to have kicked down a lady in the U-Bahnhof(subway) Hermanstraße station stairways in Oct. 2016. The man is charged now because of dangerous head-injured and Exhibitionism. He is thought to have masturberted a lady before.

*** 翻訳
    Svetoslav S. は２０１６年10月Hermanstrass駅の階段で女性を蹴り落とした被疑者である。彼は今、現在障害と露出狂という容疑で取調べを受けている。彼は女性の前でマスターベーションをしたそうだ。

*** word
    - Treter
      - unfair spielt
    - masturbierte
      - masturbate
    - heruntergetreten
      - heruntertreten
	- kick down
    - Treppe
      - stair case
    - Angeklagt
      - anklagen
	- charge
    - Exhibitionismus
      - 露出狂

** Berlin hat die Groove-Queen Joy Denalane (wieder)!
   [2017-04-25 Tue 13:44]
                           <![CDATA[Sechs Jahre stand Soul-Sängerin Joy Denalane nicht mehr auf der Bühne. Jetzt ist sie wieder da - mit neuer Platte.]]>
                      
   [[http://www.bz-berlin.de/kultur/musik/berlin-hat-die-groove-queen-joy-denalane-wieder]]


** Russland tritt nicht beim ESC in Kiew an
   [2017-04-25 Tue 13:55]
                           <![CDATA[Der ESC 2017 findet vom 9. bis 13. Mai in Kiew statt. Russland nominierte Julia Samoylova, zog seine Teilnahme aber zurück. B.Z. erklärt die Gründe.]]>
                      
   [[http://www.bz-berlin.de/kultur/musik/russland-tritt-nicht-beim-esc-in-kiew-an]]


** Netanjahu macht Drohung wahr und sagt Treffen mit Gabriel ab
   [2017-04-25 Tue 14:21]
                           <![CDATA[Diplomatischer Affront in Israel: Ministerpräsident Benjamin Netanjahu hat Außenminister Sigmar Gabriel am Dienstag nicht empfangen – ein für 16 Uhr geplantes Treffen ließ der Premier kurzfristig einfach platzen.]]>
                      
   [[http://www.bz-berlin.de/welt/netanjahu-macht-drohung-wahr-und-sagt-treffen-mit-gabriel-ab]]


** „Grey’s Anatomy”-Star Jesse Williams lässt sich scheiden
   [2017-04-25 Tue 14:23]
                           <![CDATA[Der aus der Fernsehserie „Grey's Anatomy” bekannte US-Schauspieler Jesse Williams lässt sich Medienberichten zufolge von seiner Frau scheiden. ]]>
                      
   [[http://www.bz-berlin.de/allgemein/greys-anatomy-star-jesse-williams-laesst-sich-scheiden]]


** Faye Dunaway spricht erstmals über Oscar-Panne: „War völlig verdutzt”
   [2017-04-25 Tue 14:45]
                           <![CDATA[Die Hollywood-Legende Faye Dunaway (76) hat zwei Monate nach der Oscar-Verleihung erstmals öffentlich über den großen Patzer in den letzten Showminuten gesprochen – damals verkündete sie zunächst den falschen Preisträger.]]>
                      
   [[http://www.bz-berlin.de/leute/faye-dunaway-spricht-erstmals-ueber-oscar-panne-war-voellig-verdutzt]]


** Eine Berliner Ampel gerät außer Kontrolle und schaltet, wie sie will
   [2017-04-25 Tue 14:57]
                           <![CDATA[Geht Ihnen das manchmal auch so? Sie stehen an der roten Ampel und denken: Mensch, das dauert aber heute lange, bis die auf Grün springt! Dann kann es sein, dass Sie sich an einer Kreuzung mit Straßenbahn- oder Busverkehr aufhalten. Die BVG-Fahrzeuge dürfen sich ihre Ampel nämlich selbst auf Grün schalten. Autofahrer, Radler und Fußgänger […]]]>
                      
   [[http://www.bz-berlin.de/berlin/kolumne/eine-berliner-ampel-geraet-ausser-kontrolle-und-schaltet-wie-sie-will]]


** Eisbären Tonja und Wolodja wieder vereint
   [2017-04-25 Tue 15:04]
                           <![CDATA[Nach mehr als zwei Monaten Trennung sind die Eltern des verstorbenen Eisbären Fritz wieder im Tierpark vereint.]]>
                      
   [[http://www.bz-berlin.de/berlin/eisbaeren-tonja-und-wolodja-wieder-vereint]]


** Berlin schöpft das Abi aus dem Pool
   [2017-04-25 Tue 15:30]
                           <![CDATA[Am Montag begannen die Deutschprüfungen für Berlins Abiturienten. Erstmals gibt es deutschlandweite Prüfungsaufgaben für die Schüler.]]>
                      
   [[http://www.bz-berlin.de/berlin/berlin-schoepft-das-abi-aus-dem-pool]]


** Die Berliner Polizei im Entenküken-Rettungseinsatz
   [2017-04-25 Tue 16:15]
                           <![CDATA[Erfolgreicher Rettungseinsatz für die Berliner Polizei: Einige Beamte retteten fünf Entenküken, die von ihrer Mutter getrennt worden waren, aus einem Gulli. Auch die Familienzusammenführung gelang!]]>
                      
   [[http://www.bz-berlin.de/berlin/tempelhof-schoeneberg/die-berliner-polizei-im-entenkueken-rettungseinsatz]]


** Motorradfahrer in Oberschöneweide schwer verletzt – Zeugen gesucht
   [2017-04-25 Tue 16:17]
                           <![CDATA[Ein Motorradfahrer stürzte beim Überholen eines LKW und wurde schwer verletzt.]]>
                      
   [[http://www.bz-berlin.de/berlin/treptow-koepenick/motorradfahrer-in-oberschoeneweide-schwer-verletzt-polizei-sucht-nach-zeugen]]


** Carsharing-Fahrer lässt Fußgänger schwer verletzt liegen – Unfallfahrer ermittelt
   [2017-04-25 Tue 16:50]
                           <![CDATA[Die Polizei suchte einen Unfallfahrer, der in der Nacht von Samstag zu Sonntag einen 23-Jährigen in der Kopernikusstraße erfasst hat und dann davonfuhr. Nun ist ein Verdächtiger ermittelt.]]>
                      
   [[http://www.bz-berlin.de/berlin/friedrichshain-kreuzberg/unfallflucht-carsharing-fahrer-laesst-fussgaenger-schwer-verletzt-liegen]]


** Angela Merkel und Ivanka Trump gemeinsam für mehr Frauenrechte
   [2017-04-25 Tue 16:59]
                           <![CDATA[Beim W20-Gipfel in Berlin machten sich Entscheiderinnen von Angela Merkel bis Ivanka Trump für Frauen stark.]]>
                      
   [[http://www.bz-berlin.de/berlin/merkel-und-ivanka-trump-gemeinsam-fuer-mehr-frauenrechte]]


** Alba Berlin trennt sich von Cheftrainer Caki
   [2017-04-25 Tue 17:00]
                           <![CDATA[Kurz vor den Playoffs hat sich Basketball-Bundesligist ALBA Berlin von seinem Coach Ahmet Caki getrennt. Das teilte der Hauptstadtclub am Dienstag mit.]]>
                      
   [[http://www.bz-berlin.de/berlin/alba-berlin-trennt-sich-von-cheftrainer-caki]]


** Messerattacke auf Polizisten: Zweieinhalb Jahre Haft für Schüler
   [2017-04-25 Tue 17:42]
                           <![CDATA[Nach einer Messerattacke auf einen Polizeibeamten im verganenen Jahr, ist ein 21-järiger Schüler zu zweieinhalb Jahren Haft verurteilt worden.]]>
                      
   [[http://www.bz-berlin.de/allgemein/messerattacke-auf-polizisten-zweieinhalb-jahre-haft-fuer-schueler]]


** Facebook verweigert Mutter letzte Nachrichten ihrer toten Tochter
   [2017-04-25 Tue 18:15]
                           <![CDATA[Seit Dienstag stehen sich die Mutter eines verstorbenen Mädchens und Facebook vor dem Kammergericht Berlin gegenüber. Es geht um die Herausgabe der Zugangsdaten des Mädchens.]]>
                      
   [[http://www.bz-berlin.de/berlin/facebook-verweigert-trauernder-mutter-die-letzten-nachrichten-ihrer-tochter]]


** DFB-Pokal Liveticker: Gladbach – Frankfurt 1:1
   [2017-04-25 Tue 18:59]
                           <![CDATA[Borussia Mönchengladbach empfängt Eintracht Frankfurt im Kampf um den Einzug ins DFB-Pokalfinale. Wer trifft auf Bayern oder den BVB? Alles hier im Liveticker!]]>
                      
   [[http://www.bz-berlin.de/sport/liveticker/dfb-pokal-live-gladbach-frankfurt-im-ticker]]


** Mutmaßlicher Talibankämpfer in Berlin angeklagt
   [2017-04-25 Tue 19:24]
                           <![CDATA[Einem mutmaßlichen Talibankämpfer wird vorgeworfen, zwei Menschen ermordet und sich den radikalen Islamisten angeschlossen zu haben.]]>
                      
   [[http://www.bz-berlin.de/berlin/mutmasslicher-talibankaempfer-in-berlin-angeklagt]]


** Formel 1: T-Flügel soll wieder abgeschafft werden
   [2017-04-25 Tue 20:07]
                           <![CDATA[Der Motorsport-Weltverband will die T-Flügel wieder abschaffen. Auch weitere Änderungen sind geplant.]]>
                      
   [[http://www.bz-berlin.de/berlin-sport/mehr-berlin-sport/formel-1-t-fluegel-soll-wieder-abgeschafft-werden]]

** „Jetzt bin ich ein amerikanischer Berliner“
   [2017-04-25 Tue 20:32]
                           <![CDATA[Erst mit der Enthüllung eines Porträts in der Gallerie des Abgeordnetenhauses ist die Ehrenbürgerschaft komplett. Nun wurde die Ehre dem Gründungsdirektor des Jüdischen Museums zuteil. ]]>
                      
   [[http://www.bz-berlin.de/berlin/jetzt-bin-ich-ein-amerikanischer-berliner]]






