# Created 2017-04-30 Sun 13:37
#+TITLE: USA: China warnt Nordkorea vor neuem Atomtest
#+AUTHOR: takeoka
[2017-04-28 Fri 08:30]
* USA: China warnt Nordkorea vor neuem Atomtest | USA: China warned Northkorea for new nuclear test | アメリカが発表：中国、北朝鮮に対して核実験を止めるよう警告
[2017-04-28 Fri 08:30]

Nordkoreas Machthaber Kim hat auf der Welt nur einen Verbündeten: China. Doch laut Aussagen von US-Außenminister Tillerson denkt auch Peking inzwischen über Sanktionen gegen Nordkorea nach. Gleichzeitig schloss US-Präsident Trump eine weitere Eskalation nicht aus.
[[http://www.tagesschau.de/ausland/nordkorea-469.html]]

* words
- Matchthaber
  - ruler
- Verbündeten
  - der/die Verbündete
    - ally
- die Aussage
  - statement
- Außenminister
  - Foreign
- denkt ... nach
  - nachdenken
    - think / reflecton
- schloss ... aus
  - ausschließen
    - expel
    - exclude

* translation
North Korea's ruler Kim has only one ally all over the world: China. However the loud statement from the US-Foreign Minister Tillerson reflected with Pekins also internally on the sanction against North Korea. At the same time US President Trump doesn't expel a further escalation.

# Emacs 25.0.92.2 (Org mode N/A)
