# Created 2017-04-25 Tue 23:58
#+TITLE: U-Bahn-Treter masturbierte vor zwei Frauen
#+AUTHOR: takeoka
[2017-04-25 Tue 13:35]

* U-Bahn-Treter masturbierte vor zwei Frauen | U-Bahn-Crimer masturbated before two Ladies
[2017-04-25 Tue 13:35]

訳していてホントかよ案件。B.Zがドイツの東スポと言われているのを思い出した。

Svetoslav S. soll im Oktober 2016 eine Frau im U-Bahnhof Hermannstraße die Treppe heruntergetreten haben. Angeklagt wird der Mann nun wegen gefährlicher Körperverletzung und Exhibitionismus. Er soll vor einer Frau masturbiert haben.

[[http://www.bz-berli n.de/berlin/neukoelln/u-bahn-treter-von-der-hermannstrasse-wird-auch-als-exhibitionist-angeklagt]]

* translation
Svetoslav S. is thought to have kicked down a lady in the U-Bahnhof(subway) Hermanstraße station stairways in Oct. 2016. The man is charged now because of dangerous head-injured and Exhibitionism. He is thought to have masturberted a lady before.

* 翻訳
Svetoslav S. は２０１６年10月Hermanstrass駅の階段で女性を蹴り落とした被疑者である。彼は今、現在障害と露出狂という容疑で取調べを受けている。彼は女性の前でマスターベーションをしたそうだ。

* word
- Treter
  - unfair spielt
- masturbierte
  - masturbate
- heruntergetreten
  - heruntertreten
    - kick down
- Treppe
  - stair case
- Angeklagt
  - anklagen
    - charge
- Exhibitionismus
  - 露出狂

# Emacs 25.0.92.2 (Org mode N/A)
